# Generated by Django 5.0 on 2024-01-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('formacion', 'Formación'), ('reparacion', 'Reparación'), ('producto', 'Producto')], max_length=20)),
                ('producto', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tienda')),
                ('unidades', models.IntegerField()),
                ('precio', models.FloatField()),
                ('proveedor', models.CharField(max_length=100)),
                ('fechaVenta', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tienda',
                'verbose_name_plural': 'tiendas',
            },
        ),
    ]
