# Generated by Django 5.0 on 2024-01-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='fechaVenta',
        ),
    ]
